FROM osgeo/gdal:ubuntu-small-3.0.3

ARG nrn_source=

ARG nrn_url=

ENV nrn_source ${nrn_source}

ENV nrn_url ${nrn_url}

USER root

COPY . /nrn-app

WORKDIR /nrn-app

RUN chmod u+x dl-data.sh

RUN ./dl-data.sh