name: nrnv3
channels:
  - conda-forge
  - defaults
dependencies:
  - click=7.1.2
  - fiona=1.8.18
  - gdal=3.1.4
  - geoalchemy2=0.6.3
  - geopandas=0.10.2
  - jinja2=2.11.3
  - matplotlib=3.4.2
  - numpy=1.19.5
  - pandas=1.1.5
  - pip=21.0.1
  - psycopg2=2.9.1
  - pygeos=0.10
  - python=3.9.2
  - pyyaml=5.4.1
  - requests=2.25.1
  - shapely=1.8.0
  - sphinx=3.5.1
  - sqlalchemy=1.4.21
  - tabulate=0.8.9
  - tqdm=4.58.0
