name: nrn-rrn
channels:
  - conda-forge
dependencies:
  - click=8.1.7
  - fiona=1.10.1
  - gdal=3.9.2
  - geopandas=1.0.1
  - jinja2=3.1.4
  - numpy=2.1.1
  - pandas=2.2.2
  - python=3.12.5
  - pyyaml=6.0.2
  - requests=2.32.3
  - shapely=2.0.6
  - tabulate=0.9.0
  - tqdm=4.66.5