name: nrn-rrn
channels:
  - https://jfrog.aaw.cloud.statcan.ca/artifactory/conda-forge-remote/
dependencies:
  - click=8.1.7
  - fiona=1.9.5
  - gdal=3.7.2
  - geopandas=0.14.0
  - jinja2=3.1.2
  - numpy=1.26.0
  - pandas=2.1.1
  - python=3.11.6
  - pyyaml=6.0.1
  - requests=2.31.0
  - shapely=2.0.2
  - tabulate=0.9.0
  - tqdm=4.66.1